package riogrande.view;

import javax.swing.JOptionPane;
import riogrande.DAO.ProductDAO;

/**
 *
 * @author Sofi
 */
public class ProductForm extends javax.swing.JFrame {

    private ProductDAO productDAO = new ProductDAO();

    /**
     * Creates new form ProductForm
     */
    public ProductForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        lblProductTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnReturnMenu = new javax.swing.JButton();
        btnDiscardProduct = new javax.swing.JButton();
        btnNewProduct = new javax.swing.JButton();
        lblProductDescription = new javax.swing.JLabel();
        txtSalePrice = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        txtSizeProduct = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtProductDescription = new javax.swing.JTextArea();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(170, 139, 86));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProductTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblProductTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblProductTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductTitle.setText("INGRESO DE PRODUCTOS");
        jPanel1.add(lblProductTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 470, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE DEL PRODUCTO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PRECIO DE VENTA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CONTENIDO/TAMAÑO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, -1));

        btnReturnMenu.setBackground(new java.awt.Color(51, 51, 51));
        btnReturnMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReturnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnReturnMenu.setText("MENU PRINCIPAL");
        btnReturnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 30));

        btnDiscardProduct.setBackground(new java.awt.Color(51, 51, 51));
        btnDiscardProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDiscardProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnDiscardProduct.setText("DESCARTAR");
        btnDiscardProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscardProductActionPerformed(evt);
            }
        });
        jPanel1.add(btnDiscardProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 140, 30));

        btnNewProduct.setBackground(new java.awt.Color(51, 51, 51));
        btnNewProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNewProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnNewProduct.setText("GENERAR");
        btnNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProductActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 150, 30));

        lblProductDescription.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProductDescription.setForeground(new java.awt.Color(255, 255, 255));
        lblProductDescription.setText("DESCRIPCION DEL PRODUCTO");
        jPanel1.add(lblProductDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 190, 40));

        txtSalePrice.setBackground(new java.awt.Color(255, 255, 255));
        txtSalePrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalePriceKeyTyped(evt);
            }
        });
        jPanel1.add(txtSalePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 80, -1));

        txtProductName.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 300, -1));

        txtSizeProduct.setBackground(new java.awt.Color(255, 255, 255));
        txtSizeProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSizeProductKeyTyped(evt);
            }
        });
        jPanel1.add(txtSizeProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 80, -1));

        txtProductDescription.setBackground(new java.awt.Color(255, 255, 255));
        txtProductDescription.setColumns(20);
        txtProductDescription.setRows(5);
        jScrollPane2.setViewportView(txtProductDescription);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 460, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnMenuActionPerformed

        PrincipalMenu returnMenu = new PrincipalMenu();
        returnMenu.setVisible(true);
    }//GEN-LAST:event_btnReturnMenuActionPerformed

    private void btnDiscardProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscardProductActionPerformed

        clearAll();
    }//GEN-LAST:event_btnDiscardProductActionPerformed

    private void btnNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProductActionPerformed

        if (txtProductName.getText().equals("") || txtSalePrice.getText().equals("")
                || txtSizeProduct.getText().equals("") || txtProductDescription.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
        } else {
            String message;
            String productName = txtProductName.getText();
            String salePrice = txtSalePrice.getText();
            String productSize = txtSizeProduct.getText();
            String description = txtProductDescription.getText();

            message = productDAO.createProduct(productName, salePrice, productSize, description);
            JOptionPane.showMessageDialog(this, message);
            clearAll();
        }
    }//GEN-LAST:event_btnNewProductActionPerformed

    private void txtSalePriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalePriceKeyTyped
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese numeros");

        }
    }//GEN-LAST:event_txtSalePriceKeyTyped

    private void txtSizeProductKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSizeProductKeyTyped
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese numeros");

        }
    }//GEN-LAST:event_txtSizeProductKeyTyped

    public void clearAll() {
        txtProductName.setText("");
        txtSalePrice.setText("");
        txtSizeProduct.setText("");
        txtProductDescription.setText("");

        JOptionPane.showMessageDialog(this, "El producto ha sido descartado.");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductForm().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiscardProduct;
    private javax.swing.JButton btnNewProduct;
    private javax.swing.JButton btnReturnMenu;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblProductDescription;
    private javax.swing.JLabel lblProductTitle;
    private javax.swing.JTextArea txtProductDescription;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtSalePrice;
    private javax.swing.JTextField txtSizeProduct;
    // End of variables declaration//GEN-END:variables
}
