/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package riogrande.view;

/**
 *
 * @author Sofi
 */
public class ProductTable extends javax.swing.JFrame {

    /**
     * Creates new form ProductTable
     */
    public ProductTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReturnMenu = new javax.swing.JButton();
        btnReturnMenu1 = new javax.swing.JButton();
        btnReturnMenu2 = new javax.swing.JButton();
        lblClientTableTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(170, 139, 86));
        jPanel1.setMinimumSize(new java.awt.Dimension(480, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReturnMenu.setBackground(new java.awt.Color(51, 51, 51));
        btnReturnMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReturnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnReturnMenu.setText("MENU PRINCIPAL");
        btnReturnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 30));

        btnReturnMenu1.setBackground(new java.awt.Color(51, 51, 51));
        btnReturnMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReturnMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnReturnMenu1.setText("MODIFICAR");
        btnReturnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnMenu1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturnMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 140, 30));

        btnReturnMenu2.setBackground(new java.awt.Color(51, 51, 51));
        btnReturnMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReturnMenu2.setForeground(new java.awt.Color(255, 255, 255));
        btnReturnMenu2.setText("ELIMINAR");
        btnReturnMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnMenu2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturnMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 150, 30));

        lblClientTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClientTableTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblClientTableTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClientTableTitle.setText("LISTADO DE PRODUCTOS");
        jPanel1.add(lblClientTableTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 480, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 460, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnMenuActionPerformed
        PrincipalMenu returnMenu = new PrincipalMenu();
        returnMenu.setVisible(true);
    }//GEN-LAST:event_btnReturnMenuActionPerformed

    private void btnReturnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnMenu1ActionPerformed
        PrincipalMenu returnMenu = new PrincipalMenu();
        returnMenu.setVisible(true);
    }//GEN-LAST:event_btnReturnMenu1ActionPerformed

    private void btnReturnMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnMenu2ActionPerformed
        PrincipalMenu returnMenu = new PrincipalMenu();
        returnMenu.setVisible(true);
    }//GEN-LAST:event_btnReturnMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnMenu;
    private javax.swing.JButton btnReturnMenu1;
    private javax.swing.JButton btnReturnMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblClientTableTitle;
    // End of variables declaration//GEN-END:variables
}
